name: Checks

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - uses: extractions/setup-just@v4
      - run: uv python install 3.14
      - run: uv sync --locked
      - run: just check
